- category: "hep-th"
  webhook_url_name: "WEBHOOK_HEP_TH"

- category: "hep-ph"
  webhook_url_name: "WEBHOOK_HEP_PH"

- category: "hep-lat"
  webhook_url_name: "WEBHOOK_HEP_LAT"

- category: "nucl-th"
  webhook_url_name: "WEBHOOK_NUCL_TH"

- category: "q-fin.*"
  webhook_url_name: "WEBHOOK_Q_FIN"
