name: arXiv

on:
  schedule:
    - cron: '0 0 * * 1,2,3,4,5'  # UTC
  workflow_dispatch:

jobs:
  arXiv:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Run main.py
        run: python3 main.py
        env:
          WEBHOOK_HEP_TH: ${{ secrets.WEBHOOK_HEP_TH }}
          WEBHOOK_HEP_PH: ${{ secrets.WEBHOOK_HEP_PH }}
          WEBHOOK_HEP_LAT: ${{ secrets.WEBHOOK_HEP_LAT }}
          WEBHOOK_NUCL_TH: ${{ secrets.WEBHOOK_NUCL_TH }}
          WEBHOOK_Q_FIN: ${{ secrets.WEBHOOK_Q_FIN }}
